drop table ITEM_CART;
drop table ITEM;
drop table SHIPMENT;
drop table PAYMENT;
drop table ORDERR;
drop table SELLER;
drop table CUSTOMER;
drop table SHIPPER;
drop table CATEGORYY;
drop table CART;
drop table REUSABLE_ITEM;
drop table ADDRESS;
drop table ADDRESS_ZIP;

CREATE TABLE ADDRESS_ZIP(
    AREA_CODE INT NOT NULL PRIMARY KEY,
    STATE VARCHAR(25) NOT NULL,
    COUNTRY VARCHAR(25) NOT NULL
);

CREATE TABLE ADDRESS(
   ADDRESS_ID INT NOT NULL PRIMARY KEY,
   ADDRESS_LINE1 VARCHAR (100) NOT NULL,
   ADDRESS_LINE2 VARCHAR (100),
   AREA_CODE INT NOT NULL,
   FOREIGN KEY(AREA_CODE) REFERENCES ADDRESS_ZIP(AREA_CODE)

);

CREATE TABLE REUSABLE_ITEM(
    R_ID INT NOT NULL PRIMARY KEY,
    NO_OF_TIMES_USED INT NOT NULL,
    DESCRIPTION VARCHAR(250)
);

CREATE TABLE CART(
    CART_ID INT NOT NULL PRIMARY KEY,
    NO_OF_ITEMS INT NOT NULL,
    TOTAL_COST INT NOT NULL
);

CREATE TABLE CATEGORYY(
    CATEGORY_ID INT NOT NULL PRIMARY KEY,
    CATEGORY_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE SHIPPER(
    SHIPPER_ID INT NOT NULL PRIMARY KEY,
    CONTACT_NUM INT NOT NULL
);

CREATE TABLE CUSTOMER(
   C_ID INT NOT NULL PRIMARY KEY,
   C_NAME VARCHAR (50) NOT NULL,
   USERNAME VARCHAR (20) NOT NULL,
   PASSWORD VARCHAR (20) NOT NULL,
   DATE_OF_BIRTH DATE,
   C_PHONE INT NOT NULL,
   C_EMAIL VARCHAR(25) NOT NULL,
   ADDRESS_ID INT,
   FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);

CREATE TABLE SELLER(
   S_ID INT NOT NULL PRIMARY KEY,
   S_NAME VARCHAR (50) NOT NULL,
   S_USERNAME VARCHAR (20) NOT NULL,
   S_PASSWORD VARCHAR (20) NOT NULL,
   S_PHONE INT NOT NULL,
   S_EMAIL VARCHAR(25) NOT NULL,
   ADDRESS_ID INT,
   FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);

CREATE TABLE ORDERR(
    ORDER_ID INT NOT NULL PRIMARY KEY,
    ORDER_DATE DATE NOT NULL, 
    C_ID INT NOT NULL,
    FOREIGN KEY(C_ID) REFERENCES CUSTOMER(C_ID),
    CART_ID INT NOT NULL,
    FOREIGN KEY(CART_ID) REFERENCES CART(CART_ID)
);

CREATE TABLE PAYMENT(
    PAYMENT_ID INT NOT NULL PRIMARY KEY,
    AMOUNT INT NOT NULL,
    PAYMENT_MODE VARCHAR(20) NOT NULL,
    PAYMENT_DATE DATE NOT NULL,
    ORDER_ID INT NOT NULL,
    FOREIGN KEY(ORDER_ID) REFERENCES ORDERR(ORDER_ID)
);

CREATE TABLE SHIPMENT(
    SHIPMENT_ID INT NOT NULL PRIMARY KEY,
    SHIPMENT_DATE DATE NOT NULL,
    DELIVERY_STATUS VARCHAR(20) NOT NULL,
    ADDRESS_ID INT,
    FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID),
    SHIPPER_ID INT,
    FOREIGN KEY(SHIPPER_ID) REFERENCES SHIPPER(SHIPPER_ID),
    PAYMENT_ID INT,
    FOREIGN KEY(PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID)
);

CREATE TABLE ITEM(
    ITEM_ID INT NOT NULL PRIMARY KEY,
    ITEM_NAME VARCHAR(25) NOT NULL,
    PRICE INT NOT NULL,
    S_ID INT NOT NULL, 
    FOREIGN KEY(S_ID) REFERENCES SELLER(S_ID),
    R_ID INT,
    FOREIGN KEY(R_ID) REFERENCES REUSABLE_ITEM(R_ID),
    CATEGORY_ID INT NOT NULL, 
    FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORYY(CATEGORY_ID),
    C_ID INT,
    FOREIGN KEY(C_ID) REFERENCES CUSTOMER(C_ID)
);

CREATE TABLE ITEM_CART(
    ITEM_ID INT NOT NULL,
    CART_ID INT NOT NULL,
    PRIMARY KEY(ITEM_ID, CART_ID),
    FOREIGN KEY(ITEM_ID) REFERENCES ITEM(ITEM_ID),
    FOREIGN KEY(CART_ID) REFERENCES CART(CART_ID)
);

